org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.4
supported_minecraft_versions=1.20.4
minecraft_version_range=[1.20.4,1.20.5)

mod_name=FTB Materials
mod_id=ftbmaterials

mod_version=1

neoforge_version=20.4.251
neoforge_version_range=[20.4.251,20.5.0)
neoforge_loader_version=1

archives_base_name=ftb-materials-neoforge
maven_group=dev.ftb.mods

#Deps
ftb_library_version=2004.2.0
ftb_library_version_range=[2004.2.0,2005.0.0)

jei_version=17.3.1.5

curseforge_id=1124942
