modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbmaterials"
version = "${version}"
displayName = "${mod_name}"
authors = "FTB Team"
description = '''
Adds a large collection of ores, ingots and other derived items,
as well as code to unify recipes, loot tables and worldgen to use those.
'''
#logoFile = ""

[[dependencies.ftbmaterials]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbmaterials]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbmaterials]]
modId = "ftblibrary"
type = "required"
versionRange = "${ftb_library_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ftbmaterials.mixins.json"
